config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :payments
  resources :categories
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  unauthenticated do
    root 'users#index'
   end

  authenticated :user do
  root 'categories#index', as: :authenticated_root
end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    user || User.new
    if user.admin? :admin
      can :manage, :all
    else
      can :manage, Category, author_id: user.id
      can :manage, Payment, author_id: user.id
    end
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :payments, dependent: :destroy
  has_one_attached :icon
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories

  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :name, presence: true, length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy, foreign_key: 'author_id'
  has_many :payments, dependent: :destroy, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 250 }

  def admin?(request)
    role == request.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @payments = @category.payments.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    if current_user.nil?
      redirect_to categories_path
      return
    end
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @payments = Payment.all
  end

  def show; end

  def new
    @payment = Payment.new
    @categories = Category.where(author_id: current_user.id)
  end

  def create
    @category = Category.find(params[:category_id])
    @payment = current_user.payments.new(payment_params)

    respond_to do |format|
      if @payment.save
        @payment.categories << @category
        format.html { redirect_to category_url(@category), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:name, :amount, :categories_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category Name:</strong>
    <%= category.name %>
    <span><%= category.created_at.strftime("%Y/%m/%d") %></span>
  </p>

  <p>
    <strong>Icon Name:</strong>
    <%= category.icon %>
  </p>

  <div>
    <p class="math">Sum: $<%= category.payments.sum(:amount)%></p>
  </div>

</div>

app/views/categories/_form.html.erb
<div class="wblock">
  <div class="block">
    <%= form_with(model: category) do |form| %>
      <% if category.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(category.errors.count, "error") %> not allowed this category from being saved:</h2>

          <ul>
            <% category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="ame">
        <%= form.text_field :name, class: 'catn', placeholder: 'Enter Category name' %>
      </div>
      <hr />
      <div class="ame">
      <%= form.label :icon, class: 'label-icon'%>
     <%= form.file_field :icon, class: 'caticon' %>
     </div>
      <div class="sub">
        <%= form.submit 'Add', class: 'submits' %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<nav class="mycategs">
  <ul class="categs">
    <li>
      <%= link_to '', root_path, class: "arrow-left" %>
    </li>
    <li>
      <h1 class="txt">Categories</h1>
    </li>
    <li>
      <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "destry" %>
    </li>
  </ul>
</nav>
<% @categories.each do |category| %>
  <%= link_to category_path(category) do %>
    <div class="section-container">
      <div class="icon">
       <div class="image">
        <% if category.icon.attached?%>
              <%= image_tag(category.icon) %>
            <%else%>
              <%= image_tag('group.png') %>
            <%end%>
            </div>
      </div>

      <div class="name-time">
        <p class="categories-name"><%= category.name %></p>
        <span class="date"><%= category.created_at.strftime(" 7 Apr 2023") %></span>
      </div>

      <div class="left">
        <div class="sum-delete">
          <p class="sum">Sum: $<%= category.payments.sum(:amount)%></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<div class="addnew">
  <%= link_to "Add New Category", new_category_path, class: "addnew2" %>
</div>

app/views/categories/new.html.erb
<nav class="add-category">
  <ul class="a-category">
    <li>
      <%= link_to '<', categories_path, class: "arrow-left" %>
    </li>
    <li>
      <h1 class="add">add category</h1>
    </li>
    <li>
      <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "destry" %>
    </li>
  </ul>
</nav>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<nav class="categories-nav">
  <ul class="category-nav">
    <li>
      <%= link_to '<', payments_path, class: "arrow-left" %>
    </li>
    <li>
      <h1 class="transf">Payments</h1>
    </li>
    <li>
      <%= button_to 'LOGOUT', destroy_user_session_path, method: :delete, class: "deletes" %>
    </li>
  </ul>
</nav>
<p style="color: green"><%= notice %></p>

<div class="payments">
  <div class="transaction">
   <p>Total Transactions</p>
   <p>$<%= @category.payments.sum(:amount) %></p>
  </div>
</div>

<% @payments.each do |payment| %>
  <div class="micons">
    <div class="single">
        <div class="image">
          <% if @category.icon.attached?%>
            <%= image_tag(@category.icon) %>
          <%else%>
            <%= image_tag('group.png') %>
          <%end%>
      </div>
      <div>
        <p><%= payment.name %></p>
        <p><%= payment.created_at.strftime("%Y/%m/%d %I:%M %p") %></p>  
      </div>
      <div>
        <p>$<%= payment.amount %></p>
      </div>
    </div>
  </div> 
<% end %>

<div class="addnew">
  <%= link_to "ADD NEW TRANSACTION", new_payment_path(category_id: @category.id), class: "addnew2" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetOnLine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<div class="wblock">
<div class="block">
    <%= form_with(model: payment, url: payments_url(category_id: category_id)) do |form| %>
      <% if payment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(payment.errors.count, "error") %>  this payment not allowed from being saved:</h2>

          <ul>
            <% payment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.text_field :name, class: 'f-text', placeholder: 'Enter payment name' %>
      </div>
      <hr />
      <div>
        <%= form.number_field :amount, class: 'f-text', placeholder: 'Enter Amount' %>
      </div>

      <div>
        <%= form.submit 'Add', class: 'save' %>
      </div>
    <% end %>
  </div>
</div

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <div class="payshow"
    <p class="nam">
      <strong>Name: </strong>
      <%=  payment.name %>
    </p>

    <p>
      <strong>Amount: $</strong>
      <%= payment.amount %>
    </p>

    <p class="move">
      <%= link_to "Show", payment, class: 'move' %>
    </p>
  </div>
</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<nav class="mycategs">
  <ul class="categs">
    <li>
    <%= link_to '<', categories_path, class: "arrow-left" %>

    </li>
    <li>
      <h1 class="txt">ADD PAYMENTS HERE</h1>
    </li>
    <li>
      <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "destry" %>
    </li>
  </ul>
</nav>

<p style="color: green"><%= notice %></p>

<div class="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
  <% end %>
</div>

<div class="new-payment">
  <%= link_to "New payment", new_payment_path %>
</div>

app/views/payments/new.html.erb
<nav class="add-category">
  <ul class="a-category">
    <li class='arrow-left'>
    <%= link_to '<', categories_path, class: "arrow-left" %>
    </li>
    <li>
      <h1 class="newpay">Add New Payment</h1>
    </li>
    <li>
      <%= button_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "destry" %>
    </li>
  </ul>
</nav>
<%= render partial: "form", locals: { payment: @payment, category_id: params[:category_id] } %>

<br>

<div>
  <%= link_to "<", payments_path %>
</div>

app/views/payments/show.html.erb
<nav class="add-category">
  <ul class="a-category">
    <li>
      <%= link_to '<', payments_path, class: "arrow-left" %>
    </li>
    <li>
      <h1 class="t-details">Details</h1>
    </li>
    <li>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "deletes" %>
    </li>
  </ul>
</nav
<p style="color: green"><%= notice %></p>
<div class="">
  <div class="">
    <%= render @payment %>
  </div>
</div>
<div class="backbtn">
  <%= link_to "Back to categories", categories_path, class: "back" %>
</div>

app/views/users/index.html.erb
<section class="main">
  <h1 class="title">BudgetOnLine</h1>
  <div class="btns">
    <button class="login" type="button">
      <%= link_to "SIGN IN", new_user_session_path %>
    </button>
    <button class="signup" type="button">
      <%= link_to "SIGN UP", new_user_registration_path %>
    </button>
  </div>
</section>